#!/usr/bin/env bash
# This script displays username, user id, and home directory path from /etc/passwd
while IFS=':' read -r username _ userid _ _ home _
do
    echo "$username:$userid:$home"
done < "/etc/passwd"
