#!/usr/bin/env bash
# This script displays all active IPv4 IP addresses on the machine

# Use ip command to get IPv4 addresses
# -4 filters for IPv4 addresses
# addr show lists network interfaces
# grep inet filters for lines with 'inet'
# awk extracts the IP address
# sed removes the subnet mask
ip -4 addr show | grep inet | awk '{print $2}' | sed 's/\/.*$//'
