#!/usr/bin/env bash

# This script listens on port 98 on localhost

# Check if script is run with sudo
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Listen on port 98 on localhost
nc -l 127.0.0.1 98
