#!/usr/bin/env bash
# This script listens on localhost port 98 and prints out received messages

# Use netcat (nc) to listen on port 98
# -l: listen mode
# -p: specify port
# -k: keep listening after client disconnects
nc -l -p 98
