#!/usr/bin/env bash
# Configure nginx to run as nginx user and listen on port 8080

# Change nginx user in config
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Update listen port to 8080 in default site config
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Set correct permissions
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx

# Kill any existing nginx processes
pkill apache2
pkill nginx

# Start nginx service
service nginx start
