#!/usr/bin/env bash
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/lib/nginx
pkill apache2
pkill nginx
service nginx start

